ibu cnf: add prep abort test case
openshift-kni/eco-gotests pull request #13
Opened 2024-06-03 09:40 UTC by mpmaruthu

adding ibu prep abort test case

2024-06-03 09:46 UTC, mpmaruthu commented
hello, @mcornea, I added the upgrade prep abort test case and addressed initial review comments received for the same case. Please take a look when you get a chance. Thank you!

Here is the reference of old PR and comments,
`https://github.com/openshift-kni/eco-gotests-old/pull/748`

2024-06-03 10:24 UTC, mcornea commented
lgtm

2024-06-03 10:33 UTC, mpmaruthu commented
hello @klaskosk, I added the upgrade prep abort test case and addressed your review comments received for the same case. Please take a look when you get a chance. Thank you!

Here is the reference of old PR and comments,
https://github.com/openshift-kni/eco-gotests-old/pull/748

2024-06-03 13:14 UTC, klaskosk requested changes
Just two minor comments

2024-06-03 13:53 UTC, mpmaruthu commented on tests/lca/imagebasedupgrade/cnf/upgrade-talm/tests/prep-abort-test.go
> +		AfterAll(func() {
Changes updated. Thanks!

2024-06-03 14:01 UTC, klaskosk approved these changes
/lgtm

2024-06-04 08:25 UTC, mcornea approved these changes

2024-06-04 08:25 UTC, merged