Draft: ibu cnf: add upgrade abort test case
openshift-kni/eco-gotests pull request #14
Opened 2024-06-03 13:50 UTC by mpmaruthu

adding upgrade abort test case

2024-06-05 13:58 UTC, mpmaruthu commented
@mcornea , @klaskosk , Please review this PR when you get a chance. Thanks!

2024-06-05 14:15 UTC, klaskosk requested changes
Just a few comments about eco-goinfra, otherwise looks good

2024-06-05 22:39 UTC, mpmaruthu commented on tests/lca/imagebasedupgrade/cnf/internal/cnfhelper/cnfhelper.go
> +}
Thanks. Required changes updated.

2024-06-05 22:39 UTC, mpmaruthu commented on tests/lca/imagebasedupgrade/cnf/internal/cnfhelper/cnfhelper.go
> +}
Thanks. Required changes implemented.

2024-06-05 23:12 UTC, klaskosk approved these changes
/lgtm

2024-06-06 07:13 UTC, mcornea commented
lgtm

2024-06-06 07:13 UTC, mcornea approved these changes

2024-06-06 07:14 UTC, merged