RDS Core: separate general methods from the sriov verification suite
openshift-kni/eco-gotests pull request #65
Opened 2024-06-24 18:35 UTC by elenagerman

2024-06-24 18:46 UTC, elenagerman commented
@yprokule Hi! as was discussed, PTAL

2024-06-26 10:05 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +	insureNamespaceExists(nsName)
this shouldn't be part of the method, it should only create SA, _namespace_ management should be done outside

2024-06-26 10:07 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +	insureNamespaceExists(nsName)
ditto

2024-06-26 10:08 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +func insureNamespaceExists(nsName string) {
I assume it should be `ensure` and not `insure` 😸

2024-06-27 07:56 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +		}
This should be inside `Eventually` block

2024-06-27 07:57 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +	if !deploySa.Exists() {
please add logging for a case that `SA` already exists, thanks

2024-06-27 07:59 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +		}
This should be within `Eventually` block

2024-06-27 08:00 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +		}
ditto, should be within `Eventually` block

2024-06-27 08:01 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +	}
ditto, should be within `Eventually` block

2024-06-27 08:01 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +		}
ditto

2024-06-27 08:02 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +
ditto

2024-06-27 08:03 UTC, yprokule commented on tests/system-tests/rdscore/internal/rdscorecommon/helper.go
> +		deploy, err = deploy.WithReplicas(int32(0)).Update()
no need to scale down deployment before deletion

2024-06-27 08:12 UTC, yprokule requested changes
please address new comments, thanks

2024-06-27 12:24 UTC, elenagerman commented
@yprokule I'm sorry, but I do not understand why general methods like delete/create API objects cannot be outside the sriov validation test. What if we need it for the other operator's tests? For example, configmap, rbac, and sa config can be required for the keda config.
I also do not understand what is terrible in double-checking if ns exists.
Anyway, with all the requested changes, we are returning to the original version; I do not see any value in this MR.
Thank you!

2024-06-27 12:24 UTC, closed without merging

2024-06-28 05:03 UTC, yprokule commented
> @yprokule I'm sorry, but I do not understand why general methods like delete/create API objects cannot be outside the sriov validation test. What if we need it for the other operator's tests? For example, configmap, rbac, and sa config can be required for the keda config.

@elenagerman what are U talking about? I didn't object about having some of the common methods in a dedicated file. What I said is that during your _move_ of existing methods to a new file U broke the existing logic and were asked to fix it

> I also do not understand what is terrible in double-checking if ns exists.

U don't double check but create if it's missing which again affects existing logic. And what the problem to run this at the beginning of the test or in the setup block?

> Anyway, with all the requested changes, we are returning to the original version; I do not see any value in this MR.

Again, not sure where U got the idea that we are returning to the original version - all U had to do was to address broken logic in the PR.

Feel free to reopen PR and address comments or I might piggyback on this work and adjust it myself.

Thank you!